import { Montserrat } from "next/font/google";
import "./globals.css";
import "./head.css";
import "./body.css";
import "./bodytop.css";
import "./bodybottom.css";
import "./foot.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        {children}
      </body>
    </html>
  );
}